### ISSUE TITLE
[Backend] Sessions (end-to-end)

### ISSUE THREAD

**Issue by Jma353** [cuappdev/clicker#10]
So we don't need to hit Google every time for authentication information

**Comment by Jma353** [comment]
Create here: 04b4b45082e5fdd8ac9defe980b2e60464174b27

**Comment by Jma353** [comment]
@mrkev can you continue work on this?

**Comment by mrkev** [comment]
We deferred it for a bit, but will discuss it again at the meeting tomorrow. 

Closing this since this repo is now front-end only.
