### ISSUE TITLE
[Backend] Repos for models

### ISSUE THREAD

**Issue by meganle** [cuappdev/clicker#18]
- Repository for each model

- Repos deal with creating, querying, etc. for models

**Comment by Jma353** [comment]
Before we set these up - let's work on `repos` for each type of model.  This is a good master-task though

**Comment by meganle** [comment]
Sounds good! Will start with the repos first.

**Comment by meganle** [comment]
4a996f6379ecae39492ef088f6aa1d886f6a7034
