### ISSUE TITLE
[General] Pick a testing library

### ISSUE THREAD

**Issue by mrkev** [cuappdev/clicker#21]
The three big ones most people know about;
- [ava](https://github.com/avajs/ava)
- [mocha](https://github.com/mochajs/mocha)
- [jest](https://facebook.github.io/jest/)

I've used mocha before and it gets the job done. Ava looks nicer and more modern. I've had very little exposure to jest, but I went to a talk by one of the guys from the team at facebook and apparently it's a big focus area and getting good.

If no one has any preference I'll vote for jest.

**Comment by Jma353** [comment]
We use jest for TCAT.  It's been working out pretty well, has mocking support etc
