### ISSUE TITLE
[Sockets][Start Lecture] Setup Socket Infra to allow professors to start a socket for a Lecture

### ISSUE THREAD

**Issue by Jma353** [cuappdev/clicker#6]
We want to be able to give professors to option to start a lecture (a.k.a. open a socket that everyone can connect) and close this socket when the lecture is over.

This involves: 

1. Open in the socket and subsequent students going to a page to connect to the socket
2. Having the socket correspond to a **specific identifies** (most likely the course's ID or equivalent) so we can have several courses running lectures concurrently.
3. Have some sort of validation function run on a user attempting to connect to the socket (this can be a stubbed function for now, but in the future, this function would run on initially having the user connect to the socket and either allow them to continue b/c they are part of the course, or kick them out if they are not in the course).
4. Close the socket on the professor finishing the lecture.

**NOTE**: This tasks involves no calls or to the DB, just the general socket-based infra to allow for this full interaction in the future.

**Comment by AAAstorga** [comment]
Pushed my final code and assigned @loganallen because I am busy w/ TCAT

**Comment by Jma353** [comment]
@loganallen - update here what's done currently and what you plan to do?

**Comment by loganallen** [comment]
Done:
- Starting lecture socket, students connecting and disconnecting to the open socket, specific identifier
ToDo:
- Validation function, convert to Redux workflow

**Comment by Jma353** [comment]
I've integrated redux - feel free to merge w/master and start that

**Comment by Jma353** [comment]
Updates on this?
